name: Context Examples

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "My Custom Step"
              run: |
                echo "Action! $MY_ACTION"
                echo "Actor! $MY_ACTOR"
              env:
                MY_ACTION: ${{ github.action }}
                MY_ACTOR: ${{ github.actor }}